name: forza_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # logos
    - assets/forza-motorsport-logo.svg

    # icons
    - assets/Return-left-02.svg

    # images
    - assets/BG/loading_screen_background.jpg

    # car-huracan
    - assets/BG/Huracan/bg1.png
    - assets/BG/Huracan/bg2.png
    - assets/BG/Huracan/bg3.png
    - assets/BG/Huracan/bg4.png
    - assets/BG/Huracan/bg5.png
    - assets/BG/Huracan/bg6.png
    - assets/BG/Huracan/bg7.png